name: object_recognition
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  gal: ^2.3.1
  # image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  camera: ^0.10.6
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  flutter_pytorch: ^1.0.1
  image: ^4.5.2
  flutter_vision: ^1.1.4
  # camera_android: ^0.10.9
  # tflite: ^1.1.2
  # camera_android_camerax: ^0.6.13
  # permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/medias/images/
    - assets/models/yolov5s.torchscript
    - assets/models/yolov5.tflite
    - assets/models/model_classification.pt
    - assets/labels/labels_objectDetection_Coco.txt
    - assets/labels/label_classification_imageNet.txt
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
